### ISSUE TITLE
很抱歉打扰了，但是我无论如何也没办法解决这一问题

### ISSUE THREAD

**Issue by Mariobolo** [artGlory/glory-admin#4]
我使用的是
idea + maven
### IDEA
```
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Subscription is active until February 23, 2021.
Runtime Version: 11.0.9.1+11-b1145.77 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.19.0-desktop-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 1927M
Cores: 8
Non-Bundled Plugins: com.intellij.zh, com.markskelton.one-dark-theme, github.cweijan.test-theme, org.jetbrains.kotlin
Current Desktop: Deepin
```
### MAVEN
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /data/Dev/Pro/apache-maven
Java version: 1.8.0_275, vendor: Alibaba, runtime: /data/Dev/Pro/alibaba-dragonwell/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "4.19.0-desktop-amd64", arch: "amd64", family: "unix"
```
### REPORT
```log
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.spring:webadmin:jar:${admin.version}
[WARNING] 'version' contains an expression but should be a constant. @ line 13, column 14
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------< org.spring:webadmin >-------------------------
[INFO] Building webadmin ${admin.version}
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.spring:common:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.738 s
[INFO] Finished at: 2021-01-30T23:00:52+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project webadmin: Could not resolve dependencies for project org.spring:webadmin:jar:${admin.version}: Could not find artifact org.spring:common:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by artGlory** [comment]
![image](https://user-images.githubusercontent.com/23271315/109383223-18fbc680-7920-11eb-8a14-d7d712aa91f1.png)

因为使用BOM管理，不用单个编译。直接执行这两个

**Comment by Mariobolo** [comment]
仍然报错，清理报错，安装为同样的错误
${admin.version}
![微信图片_20210301222514](https://user-images.githubusercontent.com/33422983/109511029-9e78a580-7add-11eb-902f-072373cd1ff5.png)

`
/data/Dev/Pro/alibaba-dragonwell/bin/java -Dmaven.multiModuleProjectDirectory=/data/Dev/Stu/JavaEE/glory-admin -Dmaven.home=/data/Dev/Pro/JetBrains_IDEA/plugins/maven/lib/maven3 -Dclassworlds.conf=/data/Dev/Pro/JetBrains_IDEA/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/data/Dev/Pro/JetBrains_IDEA/plugins/maven/lib/maven-event-listener.jar -javaagent:/data/Dev/Pro/JetBrains_IDEA/lib/idea_rt.jar=39715:/data/Dev/Pro/JetBrains_IDEA/bin -Dfile.encoding=UTF-8 -classpath /data/Dev/Pro/JetBrains_IDEA/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar:/data/Dev/Pro/JetBrains_IDEA/plugins/maven/lib/maven3/boot/plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2020.3.2 clean
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'version' contains an expression but should be a constant. @ org.spring:common:${common.version}, /data/Dev/Stu/JavaEE/glory-admin/common/pom.xml, line 13, column 14
[WARNING] 'dependencies.dependency.systemPath' for org.mybatis.generator:mybatis-generator-core:jar should not point at files within the project directory, ${project.basedir}/libs/mybatis-generator-core-1.3.7.jar will be unresolvable by dependent projects @ org.spring:common:${common.version}, /data/Dev/Stu/JavaEE/glory-admin/common/pom.xml, line 88, column 25
[ERROR] 'dependencies.dependency.version' for com.warrenstrange:googleauth:jar is missing. @ org.spring:common:${common.version}, /data/Dev/Stu/JavaEE/glory-admin/common/pom.xml, line 144, column 21
[WARNING] 'version' contains an expression but should be a constant. @ line 13, column 14
[WARNING] 'version' contains an expression but should be a constant. @ org.spring:webapi:${api.version}, /data/Dev/Stu/JavaEE/glory-admin/webapi/pom.xml, line 13, column 14
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.spring:common:1.0-SNAPSHOT (/data/Dev/Stu/JavaEE/glory-admin/common/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.warrenstrange:googleauth:jar is missing. @ org.spring:common:${common.version}, /data/Dev/Stu/JavaEE/glory-admin/common/pom.xml, line 144, column 21
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

进程已结束，退出代码为 1

`

**Comment by artGlory** [comment]
翻墙连外网，下载maven里面的jar

**Comment by Mariobolo** [comment]
> 翻墙连外网，下载maven里面的jar

我用的是阿里云的库，无关依赖包，全部都下载完毕了，就是无论进行如何的操作，都会提示这个问题，图片中的version类型识别失败

**Comment by artGlory** [comment]
![image](https://user-images.githubusercontent.com/23271315/109512542-2b702e80-7adf-11eb-817d-d808ec677ab8.png)

**Comment by artGlory** [comment]
你可以试试把.m2里面的所有JAR删除，然后重新下载JAR，看看行不行。

**Comment by Mariobolo** [comment]
> 你可以试试把.m2里面的所有JAR删除，然后重新下载JAR，看看行不行。

好的，我试试，没注意到谷歌的那个依赖报错，麻烦了
